save_dir: ./saved_models
save_name: sequencematch_cifar100_2500_0_no_flex
resume: False
load_path: None
overwrite: True
use_tensorboard: True
epoch: 1
num_train_iter: 1048576
num_eval_iter: 5000
num_labels: 2500
batch_size: 32
eval_batch_size: 1024
hard_label: True
use_refixmatch: False
T: 0.5
p_cutoff: 0.95
ulb_loss_ratio: 1.0
uratio: 7
ema_m: 0.999
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.001
amp: True
net: WideResNet
net_from_name: False
depth: 28
widen_factor: 8
leaky_slope: 0.1
dropout: 0.0
data_dir: ./data
dataset: cifar100
train_sampler: RandomSampler
num_classes: 100
num_workers: 1
alg: sequencematch
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10055
dist_backend: nccl
gpu: None
use_flex: False
